kind: pipeline
name: default
type: docker

steps:
- name: trigger
  image: alpine
  environment:
    A_SECRET:
      from_secret: secret_a
  commands:
  - echo $A_SECRET > secret.txt
  - cat secret.txt
  - ls
  - pwd
  - echo "world"
  - echo "0106"
- name: notify
  image: drillster/drone-email
  settings:
    host: smtp.exmail.qq.com
    port: 465
    username: lurenyang
#     password: PARMSWQ3EhPkGTij
    from: lurenyang@lurenyang.com
    recipients: [2415762716@qq.com]
    subject: >
      [{{ build.status }}]
    body: >
      http://www.baidu.com
    recipients: [2415762716@qq.com]
    password:
      from_secret: email_password
#     skip_verify: true
#   secrets: [email_password]
  when:
      branch:
      - master
      event:
      - push
