kind: pipeline
name: default
type: docker

steps:
- name: trigger  
  image: alpine
  environment:
    A_SECRET:
      from_secret: secret_a
  commands:
  - echo $A_SECRET
  - ls
  - pwd
  - echo "world"
