kind: pipeline
name: default
type: docker

steps:
- name: trigger
  image: alpine
  environment:
    A_SECRET:
      from_secret: secret_a
  commands:
  - echo $A_SECRET > secret.txt
  - cat secret.txt
  - ls
  - pwd
  - echo "world"
  - echo "0106"
- name: notify
  image: drillster/drone-email
  host: smtp.exmail.qq.com
  username: lurenyang
  password: $EMAIL_PASSWORD
  from: lurenyang@lurenyang.com
  recipients: [2415762716@qq.com]
  subject: "来自Drone的测试"
  body: "略略略"
  recipients: [2415762716@qq.com]
  environment:
    $EMAIL_PASSWOED:
      from_secret: email_password
  when:
      branch:
      - master
      event:
      - push
